services:
  db:
    image: postgres:15
    container_name: ai-pdf-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: aijazj/ai-pdf-backend:latest
    container_name: ai-pdf-backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: aijazj/ai-pdf-frontend:latest
    container_name: ai-pdf-frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  db_data:
